### ISSUE TITLE
quite a few issues

### ISSUE THREAD

**Issue by monbro** [texthtml/oauth2-provider#10]
I have a couple off issues, starting by `Pimple\ServiceProviderInterface` can not be found or `ControllerProviderInterface` can not be found. I stopped implementing at a certain point as it was a tail of errors. I tested it on "silex/silex": "~1.3" and "texthtml/oauth2-provider": "1.5.0"

**Comment by mathroc** [comment]
Hi, this package is only compatible with Pimple 3. Silex 1.3 comes with an older version of Pimple so you'll need to upgrade to Silex 2 to be able to use it. I'll update the documentation to explain that

**Comment by monbro** [comment]
makes sense, thank you, I will give it another try as I just upgraded to silex 2.0 ;)

**Comment by mathroc** [comment]
ok, feel free to report other issues or difficulties you encounter, the documentation might be lacking…

**Comment by monbro** [comment]
also you might want to specify this in the composer requeirements, so composer will complain when installed with silex 1.3

**Comment by mathroc** [comment]
well, I thought about this but I'm not sure how to do that. it does not require silex (it can be used with any framework using the symfony security component) and it could even be used with silex 1.3, the `TH\OAuth2\Pimple\OAuth2ServerProvider` class is only here to simplify the setup when using silex 2. someone could use it with silex 1.3 by regestering manually the services & routes

**Comment by monbro** [comment]
I see, that correct, then my suggestion does not make any sense. Maybe you can clearify that a bit more in the docs.

**Comment by mathroc** [comment]
that should be better now
